### PR TITLE
basic scaffolding for endpoints to create dm conversation + send dire…

### PR DESCRIPTION
**Pull request by marcoseoane**
Table structure so far:
dm_conversation:
 - user_id_from
 - user_id_to
direct_message:
- dm_conversation_id (fk)
- user_id_from
- user_id_to
- message_body
- timestamp

### CODE REVIEW

**Comment by javascriptteacher** [comment]
No need for *dm_conversation_id* should just be the key ID of the table itself, (like "id", first row)

**Comment by javascriptteacher** [comment]
Looks proper actually.

**Comment by ilyosjon09** [comment]
Why did you removed password reset endpoints?

**Comment by marcoseoane** [comment]
:/ i wouldn't have deleted them purposely i think somethings gone wrong here
________________________________

**Pull request merged**
